export enum Page {
  Home = 'Home',
  Radio = 'Radio',
  News = 'News',
  Upload = 'Upload',
  Polls = 'Polls',
  Settings = 'Settings',
  Login = 'Login',
  Weather = 'Weather',
  Sport = 'Sport',
  Profile = 'Profile',
  Events = 'Events',
  UsefulInfo = 'UsefulInfo',
  Advertising = 'Advertising',
  Admin = 'Admin',
}